In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('netflix_titles.csv')

In [4]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [42]:
# count the number of cast in each movie or Tv-Show and store it in a new column called 'num_of_cast'
data['num_of_cast'] = data['cast'].str.split(',').str.len()
data[['title', 'type', 'num_of_cast']].head(50)

                                                title     type  num_of_cast
0                                Dick Johnson Is Dead    Movie          NaN
1                                       Blood & Water  TV Show         19.0
2                                           Ganglands  TV Show          9.0
3                               Jailbirds New Orleans  TV Show          NaN
4                                        Kota Factory  TV Show          8.0
5                                       Midnight Mass  TV Show         16.0
6                    My Little Pony: A New Generation    Movie         10.0
7                                             Sankofa    Movie          8.0
8                       The Great British Baking Show  TV Show          4.0
9                                        The Starling    Movie         11.0
10                Vendetta: Truth, Lies and The Mafia  TV Show          NaN
11                                   Bangkok Breaking  TV Show         25.0
12                                       Je Suis Karl    Movie         11.0
13                   Confessions of an Invisible Girl    Movie         10.0
14                    Crime Stories: India Detectives  TV Show          NaN
15                                  Dear White People  TV Show          8.0
16  Europe's Most Dangerous Man: Otto Skorzeny in ...    Movie          NaN
17                                    Falsa identidad  TV Show         12.0
18                                          Intrusion    Movie         10.0
19                                             Jaguar  TV Show          8.0
20    Monsters Inside: The 24 Faces of Billy Milligan  TV Show          NaN
21                             Resurrection: Ertugrul  TV Show         10.0
22                                    Avvai Shanmughi    Movie          6.0
23       Go! Go! Cory Carson: Chrissy Takes the Wheel    Movie          4.0
24                                              Jeans    Movie          4.0
25                               Love on the Spectrum  TV Show          1.0
26                                     Minsara Kanavu    Movie          6.0
27                                          Grown Ups    Movie         11.0
28                                         Dark Skies    Movie         10.0
29                                           Paranoia    Movie         10.0
30                                    Ankahi Kahaniya    Movie          7.0
31                                 Chicago Party Aunt  TV Show         11.0
32                                      Sex Education  TV Show          7.0
33                                         Squid Game  TV Show         10.0
34                            Tayo and Little Wizards  TV Show          5.0
35                     The Father Who Moves Mountains    Movie         10.0
36                                     The Stronghold    Movie         10.0
37                                        Angry Birds  TV Show          5.0
38                                Birth of the Dragon    Movie          9.0
39                                       Chhota Bheem  TV Show          7.0
40             He-Man and the Masters of the Universe  TV Show         11.0
41                                               Jaws    Movie         10.0
42                                             Jaws 2    Movie         10.0
43                                             Jaws 3    Movie         10.0
44                                  Jaws: The Revenge    Movie          8.0
45                             My Heroes Were Cowboys    Movie          NaN
46                                         Safe House    Movie         10.0
47                              The Smart Money Woman  TV Show         10.0
48                                       Training Day    Movie         11.0
49                                  Castle and Castle  TV Show         14.0

In [43]:
# In the provided dataset count how many number of tv-shows and movies of each genre are there using group by or whichever other method you see fit
data.groupby('type').count()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,num_of_cast
type,,,,,,,,,,,,
Movie,6131,6131,5943,5656,5691,6131,6131,6129,6128,6131,6131,5656
TV Show,2676,2676,230,2326,2285,2666,2676,2674,2676,2676,2676,2326